version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "${HTTP_HOST_PORT}:8001"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes: 
            - mysql-data:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: "${PHP_DATABASE_NAME}"
            MYSQL_USER: "${PHP_DATABASE_USERNAME}"
            MYSQL_PASSWORD: "${PHP_DATABASE_PASSWORD}"
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        environment: 
            PHP_APP_NAME: "${PHP_APP_NAME}"
            PHP_APP_PORT: "${HTTP_HOST_PORT}"
            MYSQL_PORT: "${MYSQL_DOCKER_CONTAINER_PORT}"
            MYSQL_DATABASE: "${PHP_DATABASE_NAME}"
            MYSQL_USER: "${PHP_DATABASE_USERNAME}"
            MYSQL_PASSWORD: "${PHP_DATABASE_PASSWORD}"
        ports: 
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks: 
            - laravel
volumes:
  mysql-data: